[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "omero"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
zeroc-ice = ">=3.6.5,<4"

[pypi-dependencies]
napari = { version = ">=0.6.5, <0.7", extras = ["all"] }
omero-py = "==5.21.1"
napari-omero = { version = ">=0.5.1, <0.6", extras = ["all"] }
