[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "cellpose"
platforms = ["win-64","linux-64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
pytorch = ">=2.7.1,<3"
jupyter = ">=1.1.1,<2"

[system-requirements]
cuda = "12.8"

[pypi-dependencies]
cellpose = { version = ">=4.0.6, <5", extras = ["gui"] }

[tasks]
test-cuda = "python -c \"import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA version: {torch.version.cuda}'); print(f'Device count: {torch.cuda.device_count()}'); print(f'Current device: {torch.cuda.current_device() if torch.cuda.is_available() else None}'); print(f'Device name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else None}')\""
