[project]
name = "stardist_napari_windows"
version = "0.1.0"
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]
test-stardist = "python ./stardist_test.py"

[dependencies]
python = "3.10.*"
cudatoolkit = "11.8.*"
cudnn = "8.1.0.*"

[pypi-dependencies]
# Core dependencies
tensorflow = "==2.10.1"
stardist = "==0.9.1"
gputools = "==0.2.15"
numpy = "==1.26.0"

# Napari and GUI
napari = {version = "==0.5.4", extras = ["all", "optional", "pyqt", "pyqt5"]}
napari-console = "==0.1.1"
napari-plugin-engine = "==0.2.0"
napari-plugin-manager = "==0.1.3"
napari-svg = "==0.2.0"
pyqt5 = "==5.15.11"
pyqt5-sip = "==12.15.0"
qtconsole = "==5.6.1"
qtpy = "==2.4.2"
magicgui = "==0.9.1"
superqt = {version = "==0.6.7", extras = ["iconify"]}

# Scientific computing
scipy = "==1.14.1"
scikit-image = {version = "==0.24.0", extras = ["data"]}
pandas = "==2.2.3"
matplotlib = ">=3.10.6, <4"
csbdeep = "==0.8.1"

# Image processing
imageio = "==2.36.0"
tifffile = "==2024.9.20"
edt = "==2.4.1"

# Visualization
vispy = "==0.14.3"
pyopengl = "==3.1.7"

# Data handling
dask = {version = "==2024.11.2", extras = ["array"]}
zarr = "==2.18.3"
h5py = "==3.12.1"

# TensorFlow related
tensorboard = "==2.10.1"
keras = "==2.10.0"
tensorflow-estimator = "==2.10.0"

# Jupyter/IPython
ipykernel = "==6.29.5"
ipython = "==8.29.0"
jupyter-client = "==8.6.3"

# GPU/CUDA processing
pyopencl = "==2024.3"
reikna = "==0.8.0"
numba = "==0.60.0"

# Utilities
pydantic = "==2.9.2"
app-model = "==0.3.0"
npe2 = "==0.7.7"
typer = "==0.13.0"
click = "==8.1.7"
rich = "==13.9.4"
tqdm = "==4.67.0"
pyyaml = "==6.0.2"
psutil = "==6.1.0"
pooch = "==1.8.2"
pint = "==0.24.4"

# Development tools
sphinx = "==8.1.3"
numpydoc = "==1.8.0"

# Supporting libraries
pillow = "==11.0.0"
requests = "==2.32.3"
certifi = "==2024.8.30"
networkx = "==3.4.2"
wrapt = "==1.16.0"
packaging = "==24.2"
typing-extensions = "==4.12.2"
traitlets = "==5.14.3"
psygnal = "==0.11.1"
in-n-out = "==0.2.1"
jupyter = ">=1.1.1, <2"
