[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "mlflow"
platforms = ["win-64","linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[dependencies]
python = "3.12.*"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.7.2,<2"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.7.1,<3"

[pypi-dependencies]
mlflow = ">=3.4.0, <4"
biapy = ">=3.6.5, <4"

[tasks]
test-cuda = "python -c \"import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA version: {torch.version.cuda}'); print(f'Device count: {torch.cuda.device_count()}'); print(f'Current device: {torch.cuda.current_device() if torch.cuda.is_available() else None}'); print(f'Device name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else None}')\""
