[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "mlflow"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.7.2,<2"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
mlflow = ">=3.4.0, <4"
