[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "trackastra"
platforms = ["win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
trackastra = ">=0.3.2, <0.4"
