[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "CAREamics"
platforms = ["win-64"]
version = "0.1.0"

#250912 Does not work, issues with pytorch, careamics not matching requirment for pillow
[tasks]

[system-requirements]
cuda = "12.8"

[dependencies]
python = "==3.10"
jupyter = ">=1.1.1,<2"
#jupyter = ">=1.1.1,<2"
#matplotlib = ">=3.10.6,<4"

[feature.bioio.pypi-dependencies]
bioio-bioformats = ">=1.3.0, <2"
bioio = ">=3.0.0, <4"

[feature.imagej.pypi-dependencies]
pyimagej = ">=1.7.0, <2"

[pypi-dependencies]
pillow = "<11.3"
careamics = { version = "==0.0.15", extras = ["examples"] }
torch = "*"
torchvision = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu118"]
index-strategy = "unsafe-best-match"

[environments]
all =["bioio","imagej"]
