[workspace]
channels = ["conda-forge"]
name = "micro_sam"
platforms = ["win-64", "linux-64"] #, "osx-64", "osx-arm64"
version = "0.1.0"

[tasks]
test-cuda = "python -c \"import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA version: {torch.version.cuda}'); print(f'Device count: {torch.cuda.device_count()}'); print(f'Current device: {torch.cuda.current_device() if torch.cuda.is_available() else None}'); print(f'Device name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else None}')\""


[dependencies]
python = "3.11.*"
micro_sam = ">=1.6.1,<2"
pytorch = ">=2.7.1,<3"
numpy = "<2"
zeroc-ice = "<3.7"

[system-requirements]
cuda = "12.8"

[pypi-dependencies]
trackastra = ">=0.3.2, <0.4"
omero-py = "==5.21.1"
napari-omero = { version = ">=0.5.1, <0.6", extras = ["all"] }
